### PR TITLE
fix(fmt): Fixed formatting of the code and cleared bugs.

### PR DESCRIPTION
**Pull request by scientific-dev**
Things which i changed.

- Formatted documentation and variable names.
- Removed unwanted if and else chains.
- Added default values to the parameters instead of using if's.
- Fixed bugs.
- Instead of using classes and static methods i just configured the import and exports in `__init__.py

Some suggestions.

- Rather than making a package for list we can try to make a collection like object which was in js. and add prototypes to it. Some of the projects in python already offer it like NumPy Array.

### CODE REVIEW

**Comment by abh80** [comment]
Change are appreciated but your [fork](https://github.com/Scientific-Guy/lowdash) is behind the master of this repository.

Please update the fork and commit

**Comment by twlite** [comment]
@Scientific-Guy rebase

**Comment by scientific-dev** [comment]
Ok i have resolved conflicts now.

**Review by abh80 — APPROVED** [review]
Ok everything looks ok! We can now merge

**Pull request merged**
